server:
  port: 8300

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-service-route
          uri: lb://product-service
          predicates:
            - Path=/products/**
          filters:
            - AuthenticationFilter

        - id: order-service-route
          uri: lb://order-service
          predicates:
            - Path=/orders/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  security:
    secret-token: "umtokenlegal"
